#spring-jsp:
#  # View Resolver 설정
#  mvc:
#    view:
#      prefix: /WEB-INF/ # 요청에 응답 할 파일이 있는 경로
#      suffix: .jsp # 클라이언트로부터 요청이 오면 해당 경로에 있는 .jsp파일로 응답할 것
#   

spring:
  profiles:
    active: mariadb
  h2:
    console:
      enabled: true

---

spring:
  profiles:
    active: local
  datasource-h2:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:

---

spring:
  profiles:
    active: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/HNTEST
      username: USER
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations:
    - mappers/*.xml