spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: mariadb
  h2:
    console:
      enabled: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

---
#spring:
#  mvc:
#    view:
#      suffix: .html

---

spring:
  profiles:
    active: local
  datasource-h2:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:

---

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
---
spring:
  profiles:
    active: mariadb
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/HNTEST
      username: USER
#      username: user
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations:
    - mappers/*.xml
  type-aliases-package: com.hnworks.miniProject.domain.menu.dto
  configuration:
    map-underscore-to-camel-case: true