#spring:
#  main:
#    allow-bean-definition-overriding: true
#  profiles:
#    active: mariadb
#  h2:
#    console:
#      enabled: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

---
#spring:
#  mvc:
#    view:
#      suffix: .html

---

#spring:
#  profiles:
#    active: local
#  datasource-h2:
#    hikari:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:~/test
#      username: sa
#      password:
---

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
---
spring:
  profiles:
    active: mariadb
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/HNTEST
      username: USER
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
      


# mybatis 관련 설정
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mappers/*.xml
  # alias 설정
  # Spring Framework처럼 이름을 사용하기 편하게 바꿔주는게 아니라 길이를 줄여주는 역할.
  # IntelluJ는 자동완성을 지원하기 때문에 굳이 안써도 됨.
  # type-aliases-package: com.icia.member.dto    
    
    
    