#spring:
#  h2:
#    console:
#      enabled: true


#  datasource-h2:
#    hikari:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:~/test
#      username: sa
#      password:
#      
#  datasource:
#    hikari:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/mini?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 1234
    

spring:
  profiles:
    active: mariadb


---

spring:
  profiles:
    active: local
  datasource-h2:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:

---

spring:
  profiles:
    active: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/mini
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  batch:
#    job:
#      enabl





mybatis:
  mapper-locations:
    - mappers/*.xml