spring:
  profiles:
    active: mariadb
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/HNTEST
      username: USER
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
      
# mybatis 관련 설정
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mappers/*.xml
